version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kaspi-task
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: go_app
    depends_on:
      - db
    environment:
      PORT: "8080"
      DATABASE_URL: "postgres://postgres:password@db:5432/kaspi-task?sslmode=disable"
    command: ["go", "run", "cmd/app/app.go"]
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app

  migrate:
      build: .
      container_name: go_migrate
      depends_on:
        - db
      environment:
        DATABASE_URL: "postgres://postgres:password@db:5432/kaspi-task?sslmode=disable"
      command: [ "go", "run", "cmd/migrate/migrate.go" ]
      volumes:
        - .:/migrate
      working_dir: /migrate

volumes:
  postgres_data:
